In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras import layers


In [70]:
#pip install tensorflow

In [40]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')

In [42]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [44]:
X.shape

(9568, 4)

In [46]:
y.shape

(9568,)

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=8)

In [52]:
X_test.shape

(1914, 4)

In [54]:
X_train.shape

(7654, 4)

In [58]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
X_test

array([[ 0.71718855,  0.75243421,  0.89292634, -1.46698648],
       [ 0.70780815,  0.33035145, -0.37603808, -0.56515791],
       [ 0.22940769,  0.32799344,  0.47942474,  0.43695016],
       ...,
       [-0.90964101, -0.99170295, -0.07804907,  0.75015185],
       [-1.69893476, -1.15361924,  0.74225774,  0.55371395],
       [-0.10828675,  0.59601993, -0.60204098, -0.19906908]])

In [80]:
model = tf.keras.Sequential(
    [
        layers.Dense(6, activation='relu', name='layer1'),
        layers.Dense(6, activation='relu', name='layer2'),
        layers.Dense(1, name='outputLayer')
    ]
)

In [82]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])


In [84]:
#training the model on training set
model.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - accuracy: 0.0000e+00 - loss: 206271.0156 
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 249us/step - accuracy: 0.0000e+00 - loss: 197787.3594
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 250us/step - accuracy: 0.0000e+00 - loss: 169812.0625
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 251us/step - accuracy: 0.0000e+00 - loss: 122078.2188
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 250us/step - accuracy: 0.0000e+00 - loss: 67758.9922
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 249us/step - accuracy: 0.0000e+00 - loss: 34356.0938
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 249us/step - accuracy: 0.0000e+00 - loss: 22296.0137
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 249us/step - accuracy: 0.0000e+00 - loss: 18449.6738
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 249us/step - accuracy: 0.0000e+00 - loss: 15090.4053
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.0000e+00 - loss: 11907.2520
Epoch 11/100
240/240 ━━━

In [86]:
y_pred = model.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step
[[444.81 441.61]
 [443.92 444.19]
 [449.07 445.27]
 ...
 [468.   474.81]
 [480.27 480.07]
 [453.95 448.49]]


In [94]:
sample = np.array([[14.64, 45, 1021.78, 41.25]])
sample

array([[  14.64,   45.  , 1021.78,   41.25]])

In [96]:
sample_sc = sc.transform(sample)

In [98]:
y1 = model.predict(sample_sc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [100]:
print(y1)

[[470.06]]
